package com.codo.modelo.pojos;
// Generated 24-abr-2017 11:46:00 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Cuentas generated by hbm2java
 */
public class Cuentas implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "idCuenta", unique = true, nullable = false)
	private Integer idCuenta;

	@OneToMany(targetEntity = Monedas.class)
	@Column(name = "idMoneda", nullable = false)
	private Monedas monedas;

	@Column(name = "nombre", nullable = false)
	private String nombre;

	@Column(name = "saldo", nullable = true)
	private Double saldo;

	@Column(name = "descripcion", nullable = true)
	private String descripcion;

	@SuppressWarnings("rawtypes")
	private Set movimientosesForIdCuentaDestino = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set movimientosesForIdCuentaOrigen = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set previsionesesForIdCuentaOrigen = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set previsionesesForIdCuentaDestino = new HashSet(0);

	public Cuentas() {
	}

	public Cuentas(Monedas monedas, String nombre, Double saldo, String descripcion) {
		this.monedas = monedas;
		this.nombre = nombre;
		this.saldo = saldo;
		this.descripcion = descripcion;
	}

	@SuppressWarnings("rawtypes")
	public Cuentas(Monedas monedas, String nombre, Double saldo, String descripcion,
			Set movimientosesForIdCuentaDestino, Set movimientosesForIdCuentaOrigen, Set previsionesesForIdCuentaOrigen,
			Set previsionesesForIdCuentaDestino) {
		this.monedas = monedas;
		this.nombre = nombre;
		this.saldo = saldo;
		this.descripcion = descripcion;
		this.movimientosesForIdCuentaDestino = movimientosesForIdCuentaDestino;
		this.movimientosesForIdCuentaOrigen = movimientosesForIdCuentaOrigen;
		this.previsionesesForIdCuentaOrigen = previsionesesForIdCuentaOrigen;
		this.previsionesesForIdCuentaDestino = previsionesesForIdCuentaDestino;
	}

	public Integer getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(Integer idCuenta) {
		this.idCuenta = idCuenta;
	}

	public Monedas getMonedas() {
		return this.monedas;
	}

	public void setMonedas(Monedas monedas) {
		this.monedas = monedas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Double getSaldo() {
		return this.saldo;
	}

	public void setSaldo(Double saldo) {
		this.saldo = saldo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@SuppressWarnings("rawtypes")
	public Set getMovimientosesForIdCuentaDestino() {
		return this.movimientosesForIdCuentaDestino;
	}

	@SuppressWarnings("rawtypes")
	public void setMovimientosesForIdCuentaDestino(Set movimientosesForIdCuentaDestino) {
		this.movimientosesForIdCuentaDestino = movimientosesForIdCuentaDestino;
	}

	@SuppressWarnings("rawtypes")
	public Set getMovimientosesForIdCuentaOrigen() {
		return this.movimientosesForIdCuentaOrigen;
	}

	@SuppressWarnings("rawtypes")
	public void setMovimientosesForIdCuentaOrigen(Set movimientosesForIdCuentaOrigen) {
		this.movimientosesForIdCuentaOrigen = movimientosesForIdCuentaOrigen;
	}

	@SuppressWarnings("rawtypes")
	public Set getPrevisionesesForIdCuentaOrigen() {
		return this.previsionesesForIdCuentaOrigen;
	}

	@SuppressWarnings("rawtypes")
	public void setPrevisionesesForIdCuentaOrigen(Set previsionesesForIdCuentaOrigen) {
		this.previsionesesForIdCuentaOrigen = previsionesesForIdCuentaOrigen;
	}

	@SuppressWarnings("rawtypes")
	public Set getPrevisionesesForIdCuentaDestino() {
		return this.previsionesesForIdCuentaDestino;
	}

	@SuppressWarnings("rawtypes")
	public void setPrevisionesesForIdCuentaDestino(Set previsionesesForIdCuentaDestino) {
		this.previsionesesForIdCuentaDestino = previsionesesForIdCuentaDestino;
	}

	@Override
	public String toString() {
		return this.nombre;
	}

}