package com.codo.modelo.pojos;
// Generated 24-abr-2017 11:46:00 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Id;

/**
 * Tipos generated by hbm2java
 */
public class Tipos implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "idTipo", unique = true, nullable = false)
	private Integer idTipo;

	@Column(name = "nombre", nullable = false)
	private String nombre;

	@SuppressWarnings("rawtypes")
	private Set movimientoses = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set etiquetases = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set previsioneses = new HashSet(0);

	public Tipos() {
	}

	public Tipos(String nombre) {
		this.nombre = nombre;
	}

	@SuppressWarnings("rawtypes")
	public Tipos(String nombre, Set movimientoses, Set etiquetases, Set previsioneses) {
		this.nombre = nombre;
		this.movimientoses = movimientoses;
		this.etiquetases = etiquetases;
		this.previsioneses = previsioneses;
	}

	public Integer getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(Integer idTipo) {
		this.idTipo = idTipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@SuppressWarnings("rawtypes")
	public Set getMovimientoses() {
		return this.movimientoses;
	}

	@SuppressWarnings("rawtypes")
	public void setMovimientoses(Set movimientoses) {
		this.movimientoses = movimientoses;
	}

	@SuppressWarnings("rawtypes")
	public Set getEtiquetases() {
		return this.etiquetases;
	}

	@SuppressWarnings("rawtypes")
	public void setEtiquetases(Set etiquetases) {
		this.etiquetases = etiquetases;
	}

	@SuppressWarnings("rawtypes")
	public Set getPrevisioneses() {
		return this.previsioneses;
	}

	@SuppressWarnings("rawtypes")
	public void setPrevisioneses(Set previsioneses) {
		this.previsioneses = previsioneses;
	}

	@Override
	public String toString() {
		return this.nombre;
	}
}